#This script works and is able to display text on the screen. 
#It is able to take in a number from the user and display a joke based on the number. 
#The joke is generated by the ICTjokes model. 
#The joke is displayed on the screen in a typewriter effect. 
#The user can enter a number between 1 and 5 to get a joke based on the topic. 
#The topics are Software, Hardware, Infrastructure, Media Design, and Business



import cv2 as cv
import numpy as np
import os
from langchain_community.chat_models import ChatOllama
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

class CharacterLoader:
    def __init__(self):
        self.character_index = {}
        self.load_character_index()

    def load_character_index(self):
        dir_path = os.path.dirname(os.path.abspath(__file__))
        font_dir = os.path.join(dir_path, "font")
        files = [f for f in os.listdir(font_dir) if f[-4:] == ".csv"]
        for file in files:
            file_path = os.path.join(font_dir, file)
            data = open(file_path, "r").read()
            data = [[[255., 255., 255.] if c == '1' else [0., 0., 0.] for c in line.split(',')] for line in data.split("\n")]
            self.character_index[chr(int(file[5:-4]))] = (np.array(data), len(data[0]), len(data))

    def get_character(self, character):
        return self.character_index[character]

class TextWriter:
    def __init__(self, character_loader):
        self.character_loader = character_loader

    def put_text(self, frame, text, start):
        column_start = start[1]
        cursor = start
        char_count = 0
        for c in text:
            if c == "\n" or char_count == 50:
                cursor = [cursor[0]+6, column_start]
                char_count = 0
                if c == "\n":
                    continue
            letter = self.character_loader.get_character(c)
            frame[cursor[0]:cursor[0]+letter[2], cursor[1]:cursor[1]+letter[1]] = letter[0]
            cursor[1] += letter[1]+1
            char_count += 1

class ChatInterface:
    

    def __init__(self, model_name, stream):
        self.llm = ChatOllama(model=model_name, stream=stream)
        self.prompt = ChatPromptTemplate.from_template("Tell me a short joke about {topic}. Do not start with Sure here is the joke... or similar.")
        self.chain = self.prompt | self.llm | StrOutputParser()

    def get_response(self, topic):
        return self.chain.invoke({"topic": topic})

class TextDisplay:
    def __init__(self, text_writer):
        self.text_writer = text_writer

    def display_text(self, text):
        for i in range(len(text) + 1):
            mat = np.zeros((40, 250, 3))
            self.text_writer.put_text(mat, text[:i], [1, 0])
            cv.namedWindow('text', cv.WINDOW_NORMAL)
            cv.resizeWindow('text', 1200, 600)
            cv.imshow("text", mat)
            cv.waitKey(200)
        cv.waitKey(5000)
        cv.destroyAllWindows()

def main():
    loader = CharacterLoader()
    writer = TextWriter(loader)
    chat_interface = ChatInterface("ICTjokes", True)
    display = TextDisplay(writer)
    
    topic_dict = {
        1: "Software",
        2: "Hardware",
        3: "Infrastructure",
        4: "Media Design",
        5: "Business"
    }

    while True:
        topic_num = int(input("Please enter a number (1-Software, 2-Hardware, 3-Infrastructure, 4-Media Design, 5-Business): "))
        if topic_num not in topic_dict:
            print("Invalid number. Please enter a number between 1 and 5.")
            continue

        topic = topic_dict[topic_num]
        response = chat_interface.get_response(topic)
        display.display_text(response)

if __name__ == "__main__":
    main()
